### ISSUE TITLE
Error initializing PWMOut object (sysfs_pwmout)

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Blinka#123]
Board: Google Coral
Blinka 1.3.3
Platform Detect 1.0.3

```
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import pulseio
>>> led = pulseio.PWMOut(board.PWM3, frequency=5000, duty_cycle=0)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 55, in __init__
    self._open(pin, duty_cycle, frequency, variable_frequency)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 93, in _open
    self._set_enabled(False)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 256, in _set_enabled
    self._write_pin_attr(self._pin_enable_path, "1" if value else "0")
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 130, in _write_pin_attr
    f_attr.write(value + "\n")
OSError: [Errno 22] Invalid argument
```

**Comment by brentru** [comment]
Looks similar to https://github.com/adafruit/Adafruit_Blinka/pull/117, testing PR...

**Comment by brentru** [comment]
PR #117 fixed this issue, merged into master.
