### ISSUE TITLE
Add frequency property to busio.SPI

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Blinka#161]
From CircuitPython API:
https://circuitpython.readthedocs.io/en/4.x/shared-bindings/busio/SPI.html#busio.SPI.frequency

On a CircuitPython board:
```python
Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import board
>>> spi = board.SPI()
>>> spi.frequency
250000
>>> 
```

On a Blinka board (RPi):
```python
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> spi = board.SPI()
>>> spi.frequency
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SPI' object has no attribute 'frequency'
>>> 
```

**Comment by ladyada** [comment]
woops - yeah, you can initialize the frequency but not set/get it after - wanna do that?

**Comment by caternuson** [comment]
Just to clarify - should be a read only property.
```python
Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import board
>>> spi = board.SPI()
>>> spi.frequency
250000
>>> spi.frequency = 6000000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'SPI' object has no attribute 'frequency'
>>> 
```
I think setting requires using `configure()`, via `baudrate`:
https://circuitpython.readthedocs.io/en/4.x/shared-bindings/busio/SPI.html#busio.SPI.configure

**Comment by ladyada** [comment]
yep!

**Comment by caternuson** [comment]
Added with #164
