### ISSUE TITLE
RPI (Blinka) can't find neopixel-write

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_Blinka#31]
I upgraded to adafruit-blinks 0.2.4  and tried to access some neopixels, but it is not finding neopixel_write. Am I missing something?
```
pi@gjnpi3p-1:~/projects/blinka $ python3.6
Python 3.6.5 (default, Jul 14 2018, 16:24:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neopixel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/neopixel.py", line 34, in <module>
    from neopixel_write import neopixel_write
ModuleNotFoundError: No module named 'neopixel_write'
>>> 
```
Here is what is installed
```
pi@gjnpi3p-1:~/projects/blinka $ pip3 list
Package                          Version  
-------------------------------- ---------
Adafruit-Blinka                  0.2.4    
Adafruit-BME280                  1.0.1    
adafruit-circuitpython-bme280    2.1.0    
adafruit-circuitpython-busdevice 2.2.5    
adafruit-circuitpython-neopixel  3.3.1    
adafruit-circuitpython-rfm9x     1.1.1    
Adafruit-GPIO                    1.0.3    
adafruit-io                      2.0.15   
Adafruit-PureIO                  0.2.3    
certifi                          2018.4.16
chardet                          3.0.4    
idna                             2.7      
paho-mqtt                        1.3.1    
pip                              18.0     
requests                         2.19.1   
RPi.GPIO                         0.6.3    
setuptools                       39.0.1   
spidev                           3.2      
urllib3                          1.23     
pi@gjnpi3p-1:~/projects/blinka $ 
```

**Comment by brentru** [comment]
I just experienced the same thing, working through troubleshooting it. I think it's not included in setup.py like the other py_modules, but I could be wrong...

**Comment by jerryneedell** [comment]
Whew! Thanks for the confirmation. Glad to know it's your problem and not mine ;-)
Good luck!

**Comment by ladyada** [comment]
oops fixin!
