### ISSUE TITLE
Runtime error: Not running on a RPi - GPIO issue

### ISSUE THREAD

**Issue by djk300** [adafruit/Adafruit_Blinka#340]
I am continuing to get the Runtime error: Not running on a RPi.  I am using a Raspberry pi 4B with Ubuntu Mate 20.04.  I was using the same simple code on my old 3B+ and it worked fine.   I have tried adding the username to the gpio group and it did not fix the issue.  I have tried gpiozero and get the same error.  Not sure what to do now as I read a lot of other people with the same issue but have not yet found a solution that works for me.  Thanks.  

code is below:
import RPi.GPIO as GPIO
from hx711 import HX711

#set the pin numbers for the weight sensor on raspberry pi
hx = HX711(5, 6)

hx.set_reading_format("MSB", "MSB")

#set calibration factor aka reference unit
hx.set_reference_unit(105)
hx.reset()
hx.tare()
abc=input("scale is tared, press enter to start ->")
#print("Tare done! Add weight now...")

#begin weight count and export to google sheet
#cellcounter = 2
endloop = 10 #number of times to run the code
for k in range(endloop):
    total = 0
    endrange = 10  #number of readings to average
    for i in range(endrange):
            val = hx.get_weight(5)
            total = val + total
            #set time delay between readings
            hx.power_down()
            hx.power_up()
            time.sleep(0.1)

here is the error:

runfile('/home/4di/.config/spyder-py3/weightgpio.py', wdir='/home/4di/.config/spyder-py3')
/usr/lib/python3/dist-packages/gpiozero/pins/pi.py:129: SPISoftwareFallback: failed to initialize hardware SPI, falling back to software (error was: failed to import spidev)
  warnings.warn(
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 69, in __call__
    self = cls._instances[key]

KeyError: (8,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 71, in pin
    pin = self.pins[n]

KeyError: 8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-7-aba56dffd81c>", line 1, in <module>
    runfile('/home/4di/.config/spyder-py3/weightgpio.py', wdir='/home/4di/.config/spyder-py3')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/4di/.config/spyder-py3/weightgpio.py", line 4, in <module>
    spi = HX711()

  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)

  File "/home/4di/.local/lib/python3.8/site-packages/hx711_gpiozero/__init__.py", line 19, in __init__
    super().__init__(bits, max_voltage, **spi_args)

  File "/usr/lib/python3/dist-packages/gpiozero/spi_devices.py", line 128, in __init__
    super(AnalogInputDevice, self).__init__(shared=True, **spi_args)

  File "/usr/lib/python3/dist-packages/gpiozero/spi_devices.py", line 34, in __init__
    self._spi = self.pin_factory.spi(**spi_args)

  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 142, in spi
    return self.spi_classes[('software', shared)](self, **spi_args)

  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 72, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/gpiozero/pins/local.py", line 152, in __init__
    super(LocalPiSoftwareSPI, self).__init__(select_pin, active_high=False)

  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 47, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)

  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 375, in __init__
    pin = self.pin_factory.pin(pin)

  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 73, in pin
    pin = self.pin_class(self, n)

  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 101, in __init__
    GPIO.setup(self.number, GPIO.IN, self.GPIO_PULL_UPS[self._pull])

RuntimeError: Not running on a RPi!

**Comment by ladyada** [comment]
hi - it appears you're not using Blinka - you're running GpioZero which is a different library?
