### ISSUE TITLE
setuid/seteuid on neopixel write for applications running as a non-root effective uid.

### ISSUE THREAD

**Issue by jamesrusso** [adafruit/Adafruit_Blinka#381]
We should research the possibility of having the neopixel module seteuid back to root if it is running with an effective uid. We should also check to make sure it is running as root and give proper error message.

Right now, it gives an obsecure error message which is not very friendly. 

```
Failed to create mailbox device
: Operation not permitted
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    x = neopixel.NeoPixel(board.D18,300,auto_write=False); x.fill((255,0,0)); x.show();
  File "/home/sectional/python/lib/python3.7/site-packages/adafruit_pypixelbuf.py", line 211, in show
    return self._transmit(self._post_brightness_buffer)
  File "/home/sectional/python/lib/python3.7/site-packages/adafruit_circuitpython_neopixel-6.0.1.dev3+gcb4d02d-py3.7.egg/neopixel.py", line 177, in _transmit
  File "/home/sectional/python/lib/python3.7/site-packages/Adafruit_Blinka-5.9.2.dev1+ga3906ed-py3.7.egg/neopixel_write.py", line 25, in neopixel_write
    return _neopixel.neopixel_write(gpio, buf)
  File "/home/sectional/python/lib/python3.7/site-packages/Adafruit_Blinka-5.9.2.dev1+ga3906ed-py3.7.egg/adafruit_blinka/microcontroller/bcm283x/neopixel.py", line 74, in neopixel_write
    "ws2811_init failed with code {0} ({1})".format(resp, message)
RuntimeError: ws2811_init failed with code -9 (Failed to create mailbox device)
swig/python detected a memory leak of type 'ws2811_t *', no destructor found.
```

**Comment by makermelissa** [comment]
I'm thinking an approach such as #441 should resolve this.
