### ISSUE TITLE
type object 'gpiod.Chip' has no attribute 'OPEN_BY_NAME' in NanoPi neo core

### ISSUE THREAD

**Issue by juanCGVE** [adafruit/Adafruit_Blinka#502]
Hello everyone,

I try execute the code of the web https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage with the correct  pins. And i get the next error:

Traceback (most recent call last):
  File "led.py", line 1, in <module>
    import board
  File "/usr/local/lib/python3.7/dist-packages/board.py", line 228, in <module>
    from adafruit_blinka.board.nanopi.neocore import *
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/board/nanopi/neocore.py", line 6, in <module>
    from adafruit_blinka.microcontroller.allwinner.h3 import pin
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/allwinner/h3/pin.py", line 4, in <module>
    PA0 = Pin(0)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py", line 35, in __init__
    self._chip = gpiod.Chip("gpiochip0", gpiod.Chip.OPEN_BY_NAME)
AttributeError: type object 'gpiod.Chip' has no attribute 'OPEN_BY_NAME'

This microo have the same pins and chip than the nanoPi air and I generated the correct file for this board. It´s a copy of nanoPi air

can you help me to solve it or tell me where I can add my board?

**Comment by makermelissa** [comment]
Hi, this sounds like an issue with your libgpiod installation. Please try reinstalling and if you continue to have trouble, you can get further assistance in either https://forums.adafruit.com/ or discord.
