### ISSUE TITLE
ImportError: no module named 'typing' pi pico

### ISSUE THREAD

**Issue by Nicchessla** [adafruit/Adafruit_Blinka#686]
I am trying to run adafruits HX8357 display with the raspberry pico, running micropython using Blinka.
when I import displayio I get the error above

**Comment by tekktrik** [comment]
Can you post the error traceback?

**Comment by corlovsky** [comment]
I'm having the same issue. Please see below:

`MPY: soft reboot
Chip id:  RP2040
Board id:  RASPBERRY_PI_PICO
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
  File "/lib/displayio/__init__.py", line 20, in <module>
ImportError: no module named 'typing'
>>> `

**Comment by tekktrik** [comment]
@makermelissa should the Pico be able to support importing of `typing` like the Pi proper does?  Here's the relevant line:  https://github.com/adafruit/Adafruit_Blinka_Displayio/blob/61102c93bfb90fbccc4bc21122444531ebe2dd84/displayio/__init__.py#L20

**Comment by makermelissa** [comment]
@tekktrik I'm not sure, but if there is an option of not requiring it, that would be ideal since there's already so little extra space.

**Comment by tekktrik** [comment]
I'm more surprised because I don't think `typing` exists and I'm surprised it might only be an issue now.  I can do some more digging.

**Comment by Neradoc** [comment]
Is displayio even compatible with Micropython ? It has seemingly never been tested there.
It's not an issue to use typing without guards in a library that is not supported on MP.
This should probably be an issue in https://github.com/adafruit/Adafruit_Blinka_Displayio
