### ISSUE TITLE
Unable to recognize board radxa Rock 4 SE

### ISSUE THREAD

**Issue by DavidTingley** [adafruit/Adafruit_Blinka#700]
I am unable to detect the correct board/chip when trying to run I2C devices on the Radxa Rock 4 SE. 

I am running this image: `https://github.com/radxa-build/rock-4se/releases/download/20230312-1521/rock-4se_debian_bullseye_kde_b33.img.xz` 

```
from adafruit_platformdetect import Detector
detector = Detector()
print("Chip id: ", detector.chip.id)
print("Board id: ", detector.board.id)
```
returns: 
```
Chip id:  RK3399
Board id:  None
```

When I try to import the board module:

```
>>> import board
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radxa/.local/lib/python3.9/site-packages/board.py", line 354, in <module>
    raise NotImplementedError(
NotImplementedError: 
        Adafruit-PlatformDetect version 3.49.0 was unable to identify the board and/or
        microcontroller running the Linux platform. Please be sure you
        have the latest packages running:
        'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'
```

**Comment by makermelissa** [comment]
Fixed by #791.
