### ISSUE TITLE
board not supported

### ISSUE THREAD

**Issue by dakhunter** [adafruit/Adafruit_Blinka#72]
I tried to import adafruit_motorkit in python3
the compiler throws back the following errors:
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_motorkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/adafruit_circuitpython_motorkit-1.2.4.dev0+g6f2d8ad.d20181230-py3.5.egg/adafruit_motorkit.py", line 59, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_Blinka-1.1.0-py3.5.egg/board.py", line 65, in <module>
NotImplementedError: Board not supported
```
I have a Raspberry Pi 3 B model. As stated in the adafruit_blinka/board.py, this board is supported. This RPi worked before with the adafruit_motorkit library but for some reason it's not working now when I reinstalled the Operating system
Any help would be great

**Comment by dakhunter** [comment]
And I think that revcode is because my RPi is shipped from UK
https://www.raspberrypi-spy.co.uk/2012/09/checking-your-raspberry-pi-board-version/
![image](https://user-images.githubusercontent.com/1934867/50550481-48cdb780-0c4c-11e9-8d03-57217b3e6cff.png)

**Comment by ladyada** [comment]
nope, its because of the `warranty bit` - please hold! :)

**Comment by dakhunter** [comment]
Oh. I did some modification on my /boot/config.txt then. But it's mostly for gpu_mem, and screen resolution to fit my teamviewer

**Comment by ladyada** [comment]
ok try `sudo pip install  Adafruit-PlatformDetect --upgrade` so you have 0.0.9 and try again

**Comment by dakhunter** [comment]
Thank you very much. The problem is resolved. Still kinda strange for me when I did the exact thing like I did before Christmas and it did not work
Well, I guess that will remain a mystery of programming lol
