### ISSUE TITLE
RPi 5 compatibility

### ISSUE THREAD

**Issue by bujna94** [adafruit/Adafruit_Blinka#812]
Doesn't work with RPi 5. Any chance of updating it?

```
Traceback (most recent call last):
  File "/home/scotty/test.py", line 62, in <module>
    pixels.show()
  File "/usr/local/lib/python3.11/dist-packages/adafruit_pixelbuf.py", line 204, in show
    return self._transmit(self._post_brightness_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scotty/neopixel_test.py", line 180, in _transmit
    neopixel_write(self.pin, buffer)
  File "/usr/local/lib/python3.11/dist-packages/neopixel_write.py", line 42, in neopixel_write
    return _neopixel.neopixel_write(gpio, buf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/adafruit_blinka/microcontroller/bcm283x/neopixel.py", line 66, in neopixel_write
    ws.ws2811_channel_t_gpionum_set(channel, gpio._pin.id)
TypeError: in method 'ws2811_channel_t_gpionum_set', argument 2 of type 'int'
swig/python detected a memory leak of type 'ws2811_t *', no destructor found.
```

**Comment by jepler** [comment]
Ah, closing as it was already reported at https://github.com/adafruit/Adafruit_Blinka/issues/747 -- please subscribe to that issue for any status updates!
