### ISSUE TITLE
USB C to I2C converter not being recognized in command prompt

### ISSUE THREAD

**Issue by Duh-Inc** [adafruit/Adafruit_Blinka#909]
### Board Name

ft232h and win 11 pc

### Steps

in this [tuto](https://learn.adafruit.com/circuitpython-libraries-on-any-computer-with-mcp2221/windows) I got all the way to the step where i install blinka. i had no errors. the tuto told me that i could permanently change a setting, so i decided to open up the system 32 cmd to run that specific command (i have no idea if that even would work tho) and closed out of it. i didnt read ahead, but when i did, irealized i shouldn't have done that. No matter, i just re-opened normal cmd, ran the command again to make sure it would be working, and ran import board. then i got this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\board.py", line 21, in <module>
    from adafruit_blinka.agnostic import board_id, detector
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\adafruit_blinka\agnostic\__init__.py", line 21, in <module>
    chip_id = detector.chip.id
              ^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\adafruit_platformdetect\chip.py", line 95, in id
    raise RuntimeError(
RuntimeError: BLINKA_MCP2221 environment variable set, but no MCP2221 device found

i have the board plugged in with a usb a - c cable from my pc. what could i be doing wrong?

### Additional information

I dont know if i did this correctly, im not very good with this sort of stuff (both cmd and explaining)

**Comment by FoamyGuy** [comment]
It looks like Blinka is not seeing the FT322H device, the tutorial you followed is for the MCP2221 which is a different albeit similarly capable device. 

Try following this guide: https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/windows it looks like the F2232H requires some extra setup steps for use with windows.
